/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTBreakStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTBreakStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}