/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTContinueStatement extends SimpleNode {
  public ASTContinueStatement(int id) {
    super(id);
  }

  public ASTContinueStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTContinueStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTContinueStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}