/* Generated By:JJTree: Do not edit this line. ASTCompositeReference.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTCompositeReference extends SimpleNode {
  public ASTCompositeReference(int id) {
    super(id);
  }

  public ASTCompositeReference(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTCompositeReference(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTCompositeReference(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}