/* Generated By:JJTree: Do not edit this line. ASTConditionalExpression.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTConditionalExpression extends SimpleNode {
  public ASTConditionalExpression(int id) {
    super(id);
  }

  public ASTConditionalExpression(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTConditionalExpression(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTConditionalExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}