/* Generated By:JJTree: Do not edit this line. ASTFormalParameterList.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTFormalParameterList extends SimpleNode {
  public ASTFormalParameterList(int id) {
    super(id);
  }

  public ASTFormalParameterList(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTFormalParameterList(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTFormalParameterList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  // JMCL
  public String [] getArguments() {
      int n = jjtGetNumChildren();
      String [] args = new String[n];
      for (int i=0; i<n; i++) {
           ASTIdentifier idNode = (ASTIdentifier) (jjtGetChild(i));
           args[i]=idNode.getName();
      }
      return args;
  }
}