/* Generated By:JJTree: Do not edit this line. ASTForVarStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTForVarStatement extends SimpleNode {
  public ASTForVarStatement(int id) {
    super(id);
  }

  public ASTForVarStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTForVarStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTForVarStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}