/* Generated By:JJTree: Do not edit this line. ASTForStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTForStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTForStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}