/* Generated By:JJTree: Do not edit this line. ASTOrExpressionSequence.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTOrExpressionSequence extends SimpleNode {
  public ASTOrExpressionSequence(int id) {
    super(id);
  }

  public ASTOrExpressionSequence(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTOrExpressionSequence(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTOrExpressionSequence(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}