/* Generated By:JJTree: Do not edit this line. ASTOperator.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTOperator extends SimpleNode {
    
  private int operatorCode = EOF;
  
  public ASTOperator(int id) {
    super(id);
  }

  public ASTOperator(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTOperator(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTOperator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  // JMCL
  public void setOperator(int operatorCode) {
      this.operatorCode = operatorCode;
  }
  public int getOperator() {
      return operatorCode;
  }
  
  public String toString() {
      return "<" + tokenImage[operatorCode] + ">";
  }

}