/* Generated By:JJTree: Do not edit this line. ASTPropertyValueReference.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTPropertyValueReference extends SimpleNode {
  public ASTPropertyValueReference(int id) {
    super(id);
  }

  public ASTPropertyValueReference(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTPropertyValueReference(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTPropertyValueReference(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}