/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTReturnStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTReturnStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}