/* Generated By:JJTree: Do not edit this line. ASTStatementList.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTStatementList extends SimpleNode {
  public ASTStatementList(int id) {
    super(id);
  }

  public ASTStatementList(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTStatementList(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTStatementList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}