/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaration.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTVariableDeclaration extends SimpleNode {
  public ASTVariableDeclaration(int id) {
    super(id);
  }

  public ASTVariableDeclaration(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTVariableDeclaration(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTVariableDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}