/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */

package FESI.AST;

import FESI.Parser.*;

public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(EcmaScript p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new ASTWhileStatement(id);
  }

  public static Node jjtCreate(EcmaScript p, int id) {
      return new ASTWhileStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}