/* Generated By:JJTree: Do not edit this line. EcmaScriptTreeConstants.java */

package FESI.AST;

public interface EcmaScriptTreeConstants
{
  public int JJTLITERAL = 0;
  public int JJTIDENTIFIER = 1;
  public int JJTVOID = 2;
  public int JJTTHISREFERENCE = 3;
  public int JJTCOMPOSITEREFERENCE = 4;
  public int JJTFUNCTIONCALLPARAMETERS = 5;
  public int JJTPROPERTYVALUEREFERENCE = 6;
  public int JJTPROPERTYIDENTIFIERREFERENCE = 7;
  public int JJTALLOCATIONEXPRESSION = 8;
  public int JJTOPERATOR = 9;
  public int JJTPOSTFIXEXPRESSION = 10;
  public int JJTUNARYEXPRESSION = 11;
  public int JJTBINARYEXPRESSIONSEQUENCE = 12;
  public int JJTANDEXPRESSIONSEQUENCE = 13;
  public int JJTOREXPRESSIONSEQUENCE = 14;
  public int JJTCONDITIONALEXPRESSION = 15;
  public int JJTASSIGNMENTEXPRESSION = 16;
  public int JJTEXPRESSIONLIST = 17;
  public int JJTSTATEMENT = 18;
  public int JJTSTATEMENTLIST = 19;
  public int JJTVARIABLEDECLARATION = 20;
  public int JJTIFSTATEMENT = 21;
  public int JJTWHILESTATEMENT = 22;
  public int JJTFORSTATEMENT = 23;
  public int JJTEMPTYEXPRESSION = 24;
  public int JJTFORVARSTATEMENT = 25;
  public int JJTFORINSTATEMENT = 26;
  public int JJTFORVARINSTATEMENT = 27;
  public int JJTCONTINUESTATEMENT = 28;
  public int JJTBREAKSTATEMENT = 29;
  public int JJTRETURNSTATEMENT = 30;
  public int JJTWITHSTATEMENT = 31;
  public int JJTFUNCTIONDECLARATION = 32;
  public int JJTFORMALPARAMETERLIST = 33;
  public int JJTPROGRAM = 34;


  public String[] jjtNodeName = {
    "Literal",
    "Identifier",
    "void",
    "ThisReference",
    "CompositeReference",
    "FunctionCallParameters",
    "PropertyValueReference",
    "PropertyIdentifierReference",
    "AllocationExpression",
    "Operator",
    "PostfixExpression",
    "UnaryExpression",
    "BinaryExpressionSequence",
    "AndExpressionSequence",
    "OrExpressionSequence",
    "ConditionalExpression",
    "AssignmentExpression",
    "ExpressionList",
    "Statement",
    "StatementList",
    "VariableDeclaration",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "EmptyExpression",
    "ForVarStatement",
    "ForInStatement",
    "ForVarInStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "WithStatement",
    "FunctionDeclaration",
    "FormalParameterList",
    "Program",
  };
}
